[[manager.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg --args='rg'"
desc = "find file by content"

[[manager.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by name"
