theme = "tokyonight"

[editor]
auto-save = true
true-color = true
idle-timeout = 0
completion-trigger-len = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name" ,"read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "version-control"]

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
";" = "command_mode"
d = ["yank_joined_to_clipboard", "yank", "delete_selection"]
y = ["yank_joined_to_clipboard", "yank"]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
