[[language]]
name = "python"
scope = "source.python"
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }
language-servers = [
  # { name = "pyright" },
  { name = "pylsp" },
  { name = "ruff-lsp" },
]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
lint = true
inlayHint.enable = true

[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins]
rope.enabled = true
pylsp_mypy.enabled = true
pylsp_mypy.live_mode = true

pylint.enabled = false
autopep8.enabled = false
yapf.enabled = false
mccabe.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
flake8.enabled = false
