[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }
language-servers = [
  { name = "pyright" },
  { name = "ruff-lsp" },
]

[language-server.pyright.config]
lint = true
inlayHint.enable = true

