[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff", "ty", "pyrefly"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "markdown"] }

[[language]]
name = "latex"
language-servers = [{ name = "texlab" }]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
lint = true
inlayHint.enable = true

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true
